name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js (v16)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Set Git user identity
        run: |
          git config --global user.name "MujtabaJunaid"
          git config --global user.email "mujtabajunaid412@gmail.com"

      - name: Set up Git credentials with token
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/MujtabaJunaid/Chatbot-RAG-JS-React.git

      - name: Deploy to GitHub Pages
        run: |
          echo "Deploying to GitHub Pages"
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
